from src.database.db_manager import DBManager


def up(db_manager: DBManager):
    db_manager.execute(
        '''
        CREATE TABLE IF NOT EXISTS achievements (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code TEXT NOT NULL UNIQUE,
            name TEXT NOT NULL,
            description TEXT NOT NULL,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            xp_value INTEGER NOT NULL DEFAULT 0,
            created_at TIMESTAMPTZ DEFAULT NOW(),
            updated_at TIMESTAMPTZ DEFAULT NOW()
        )
        '''
    )

    db_manager.execute(
        '''
        CREATE TABLE IF NOT EXISTS user_achievements (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT NOT NULL,
            achievement_id INTEGER NOT NULL REFERENCES achievements(id)
            ON DELETE CASCADE,
            metadata JSONB NOT NULL DEFAULT '{}',
            earned_at TIMESTAMPTZ DEFAULT NOW(),
            CONSTRAINT uq_user_achievement UNIQUE(user_id, achievement_id)
        )
        '''
    )

    db_manager.execute(
        '''
        CREATE INDEX IF NOT EXISTS idx_user_achievements_user_id
        ON user_achievements(user_id)
        '''
    )

    # Award achievement XP to user on insert into user_achievements
    db_manager.execute(
        '''
        CREATE OR REPLACE FUNCTION award_achievement_xp_fn()
        RETURNS TRIGGER AS $$
        DECLARE
            v_xp INTEGER;
        BEGIN
            SELECT COALESCE(xp_value, 0) INTO v_xp FROM achievements
            WHERE id = NEW.achievement_id;
            UPDATE users
            SET total_xp = total_xp + COALESCE(v_xp, 0),
                updated_at = NOW()
            WHERE id = NEW.user_id;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        '''
    )
    db_manager.execute(
        '''
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_trigger
                WHERE tgname = 'trg_award_achievement_xp_on_insert'
            ) THEN
                CREATE TRIGGER trg_award_achievement_xp_on_insert
                AFTER INSERT ON user_achievements
                FOR EACH ROW
                EXECUTE FUNCTION award_achievement_xp_fn();
            END IF;
        END $$;
        '''
    )
