from src.database.db_manager import DBManager


def up(db_manager: DBManager):
    # Create user_quests table
    db_manager.execute('''
        CREATE TABLE IF NOT EXISTS user_quests (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT NOT NULL,
            activity_id INTEGER NOT NULL,
            deadline TIMESTAMPTZ NOT NULL,
            is_new_bonus BOOLEAN NOT NULL DEFAULT FALSE,
            created_at TIMESTAMPTZ DEFAULT NOW(),
            CONSTRAINT fk_uq_user FOREIGN KEY (user_id)
                REFERENCES users(id) ON DELETE CASCADE,
            CONSTRAINT fk_uq_activity FOREIGN KEY (activity_id)
                REFERENCES activities(id) ON DELETE CASCADE
        )
    ''')

    # Add index for quick lookups by user (usually we only have 1 active quest per user)
    db_manager.execute('''
        CREATE INDEX IF NOT EXISTS idx_user_quests_user_id
        ON user_quests(user_id)
    ''')


def down(db_manager: DBManager):
    db_manager.execute('DROP TABLE IF EXISTS user_quests')
    db_manager.execute(
        'DELETE FROM migrations '
        'WHERE filename = "20260218_213000_create_user_quests.py"'
    )
