# Generated by Django 6.0.3 on 2026-03-04 20:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                (
                    'last_login',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='last login'
                    ),
                ),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('display_name', models.TextField()),
                ('total_xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                (
                    'email',
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.TextField(unique=True)),
                ('category', models.TextField()),
                ('xp_value', models.IntegerField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'activities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('note', models.TextField(blank=True, null=True)),
                ('date_occurred', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'activity_records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LevelThreshold',
            fields=[
                ('level', models.IntegerField(primary_key=True, serialize=False)),
                ('xp_required', models.IntegerField()),
            ],
            options={
                'db_table': 'level_thresholds',
                'managed': False,
            },
        ),
    ]
